# Generated by Django 4.0.2 on 2022-04-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradedate', models.CharField(blank=True, db_column='TradeDate', max_length=10, null=True)),
                ('spy', models.FloatField(blank=True, db_column='SPY', null=True)),
                ('gld', models.FloatField(blank=True, db_column='GLD', null=True)),
                ('amzn', models.FloatField(blank=True, db_column='AMZN', null=True)),
                ('goog', models.FloatField(blank=True, db_column='GOOG', null=True)),
                ('kpti', models.FloatField(blank=True, db_column='KPTI', null=True)),
                ('gild', models.FloatField(blank=True, db_column='GILD', null=True)),
                ('mpc', models.FloatField(blank=True, db_column='MPC', null=True)),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
    ]
